version: '3.4'

volumes:
  datafiles:

networks:
  mysqlNET:
  SmartSchoolNET:

services:
  database:
    image: mysql:5.7.34
    ports:
      - "3306:3306"
    volumes:
      - datafiles:/var/lib/mysql/
      - ${PWD}/:/var/lib/mysql/
    restart: always
    networks:
      - mysqlNET
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - bind-address=0.0.0.0
    container_name: smartschoolmysql

  smartschool.webapi:
    build:
      context: .
      dockerfile: SmartSchool.WebApi/Dockerfile
    depends_on:
      - database
    ports:
      - "5000:80"
    networks:
      - mysqlNET
      - SmartSchoolNET
    environment: 
      - DBASE=${MYSQL_CONNECTION_STRING}
      - DBHOST=database
      - BASEURL=${BASE_URL}
    image: smartschool:dev
    container_name: smartschoolwebapi